name=crafttools
title=CraftTools
description="""
Simple tools that automatically return and lose a bit of durability each time they're crafted with and stay in the grid.

The maximum uses of each tool can be configured in the settings. Recipes will be available if the 'default' mod is present.
"""

optional_depends=default